App\Entity\Army:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        soldiers:
            targetEntity: Soldier
            mappedBy: army
    manyToOne:
        war:
            targetEntity: War
            inversedBy: armies
    fields:
        tag:
            type: string
            length: 50
            nullable: false