App\Entity\BattleOutcome:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        outcome:
            type: string
            nullable: false
            options:
                default: 'survived'
    manyToOne:
        battle:
            targetEntity: Battle
            inversedBy: outcomes
            joinColumn:
                nullable: false
        soldier:
            targetEntity: Soldier
            inversedBy: battleOutcomes
            joinColumn:
                nullable: false
