App\Entity\BattleOutcome:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        survived:
            type: boolean
            nullable: false
            options:
                default: 1
