App\Entity\Cannon:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        army:
            targetEntity: Army
            inversedBy: cannons
            joinColumn:
                nullable: false