App\Entity\Soldier:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        army:
            targetEntity: Army
            inversedBy: soldiers
    fields:
        experience:
            type: integer
            nullable: false
            options:
                default: 0
        alive:
            type: boolean
            nullable: false
            options:
                default: 1
