App\Entity\War:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        battles:
            targetEntity: Battle
            mappedBy: war
